// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://lqateupwzmedotgvcacp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxxYXRldXB3em1lZG90Z3ZjYWNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0ODg1NzAsImV4cCI6MjA3MzA2NDU3MH0.hjG-P6xgZAqaKv9NKg5U2xcOovAFkwrLXGZqV9B1E9g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);